### ISSUE TITLE
spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by mfominov** [jfrog/jfrog-vscode-extension#20]
I'm trying to scan JavaScript project and see this error in extension Output console.

VsCode about
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

**Comment by yahavi** [comment]
Thanks for reporting this issue, @mfominov.

Please help us figuring it out soon by providing more information:
Do you have any more information about the error, like stack-trace?
Can you run `npm ls` without errors?
Does this issue persists each time you click on `refresh`?

**Comment by mfominov** [comment]
ERR - 12:24:27 PM] Error
spawnSync /bin/sh ENOBUFS
Error: spawnSync /bin/sh ENOBUFS
	at Object.spawnSync (internal/child_process.js:1041:20)
	at spawnSync (child_process.js:615:24)
	at Object.execSync (child_process.js:660:15)
	at Object.<anonymous> (electron/js2c/asar.js:744:23)
	at Object.execSync (electron/js2c/asar.js:744:23)
	at NpmTreeNode.refreshDependencies (/Users/maksimfominov/.vscode/extensions/jfrog.jfrog-vscode-extension-1.1.1/out/main/treeDataProviders/dependenciesTree/npmTreeNode.js:27:39)
	at Function.createDependenciesTrees (/Users/maksimfominov/.vscode/extensions/jfrog.jfrog-vscode-extension-1.1.1/out/main/utils/npmUtils.js:85:34)
	at async Function.createDependenciesTrees (/Users/maksimfominov/.vscode/extensions/jfrog.jfrog-vscode-extension-1.1.1/out/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.js:8:9)
	at async /Users/maksimfominov/.vscode/extensions/jfrog.jfrog-vscode-extension-1.1.1/out/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.js:144:13

**Comment by yahavi** [comment]
Yes. 
Can you please also check if you can run on your project `npm ls` without errors?
Does this issue persists each time you click on refresh?
Thanks.

**Comment by mfominov** [comment]
Yes, every refresh.
No errors on npm ls, but maybe problem in time out.
When i run npm ls it stucks for 1-3s.

**Comment by yahavi** [comment]
@mfominov we are planning to relase a patch version soon with the fix.
We'll keep you updated.

**Comment by mfominov** [comment]
thx alot

**Comment by yahavi** [comment]
@mfominov,
JFrog VS-Code extension 1.1.2 is released. Feel free to upgrade.
We'll appreciate your feedback for that!
